apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base

patches:
- path: hpa.yaml
images:
- name: ghcr.io/victormilk/poc-service
  newName: ghcr.io/victormilk/poc-service
  newTag: af6149009d8956af4ec756472a92a954abf0b4b1
