apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-service-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/victormilk/poc-service
    targetRevision: HEAD
    path: k8s/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}