apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-service
  labels:
    app: poc-service
spec:
  selector:
    matchLabels:
      app: poc-service
  template:
    metadata:
      name: poc-service
      labels:
        app: poc-service
    spec:
      containers:
        - name: poc-service
          image: ghcr.io/victormilk/poc-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
